type TileDefinition = {
  model: string;
  correction?: {
    position?: [x: number, y: number, z: number];
    rotation?: [x: number, y: number, z: number];
    scale?: number | [x: number, y: number, z: number];
  };
};

const TileMaps: Record<string, Record<number, string | TileDefinition | TileDefinition[]>> = {
  td: {
    100: "tile",
    101: "tile-bump",
    103: "tile-corner-inner",
    104: "tile-corner-inner",
    105: "tile-corner-large",
    106: "tile-corner-outer",
    107: "tile-corner-round",
    108: "tile-corner-square",
    109: "tile-crossing",
    110: "tile-crystal",
    111: "tile-dirt",
    112: "tile-end",
    113: "tile-end-round",
    114: "tile-hill",
    115: "tile-river-bridge",
    116: "tile-river-corner",
    117: "tile-river-slope",
    118: "tile-river-slope-large",
    119: "tile-river-straight",
    120: "tile-river-transition",
    121: "tile-river-waterfall",
    122: "tile-rock",
    123: "tile-slope",
    124: "tile-spawn",
    125: "tile-spawn-end",
    126: "tile-spawn-end-round",
    127: "tile-spawn-round",
    128: "tile-split",
    129: "tile-straight",
    130: "tile-straight-slope",
    131: "tile-straight-slope-large",
    132: "tile-transition",
    133: "tile-tree",
    134: "tile-tree-double",
    135: "tile-tree-quad",
  },
  prototype: {
    100: [],
    101: "animal-bison",
    102: "animal-dog",
    103: "animal-horse",
    104: "button-floor-round",
    105: "button-floor-round-small",
    106: "button-floor-square",
    107: "button-floor-square-small",
    108: "coin",
    109: "column",
    110: "column-low",
    111: "column-rounded",
    112: "column-rounded-low",
    113: "column-triangle",
    114: "column-triangle-low",
    115: "crate",
    116: "crate-color",
    117: "door-garage",
    118: "door-rotate",
    119: "door-sliding",
    120: "door-sliding-double",
    121: "door-sliding-double-round",
    122: "door-sliding-double-wide",
    123: "figurine",
    124: "figurine-cube",
    125: "figurine-cube-detailed",
    126: "figurine-large",
    127: "flag",
    128: "floor-diagonal",
    129: "floor-small-diagonal",
    130: "floor-small-square",
    131: "floor-square",
    132: "floor-thick",
    133: "floor-thick-corner-diagonal",
    134: "floor-thick-corner-round",
    135: "floor-thick-corner-rounded",
    136: "hat-cap",
    137: "hat-hard",
    138: "indicator-doorway",
    139: "indicator-round-a",
    140: "indicator-round-b",
    141: "indicator-round-c",
    142: "indicator-round-d",
    143: "indicator-round-e",
    144: "indicator-round-f",
    145: "indicator-special-area",
    146: "indicator-special-arrow",
    147: "indicator-special-cross",
    148: "indicator-special-lines",
    149: "indicator-square-a",
    150: "indicator-square-b",
    151: "indicator-square-c",
    152: "indicator-square-d",
    153: "indicator-square-e",
    154: "indicator-square-f",
    155: "ladder",
    156: "ladder-color",
    157: "ladder-top",
    158: "lever-double",
    159: "lever-single",
    160: "number-0",
    161: "number-1",
    162: "number-2",
    163: "number-3",
    164: "number-4",
    165: "number-5",
    166: "number-6",
    167: "number-7",
    168: "number-8",
    169: "number-9",
    170: "number-double-0",
    171: "number-double-1",
    172: "number-double-2",
    173: "number-double-3",
    174: "number-double-4",
    175: "number-double-5",
    176: "number-double-6",
    177: "number-double-7",
    178: "number-double-8",
    179: "number-double-9",
    180: "pipe",
    181: "pipe-corner",
    182: "pipe-half",
    183: "pipe-half-section",
    184: "pipe-section",
    185: "pipe-split",
    186: "shape-cube",
    187: "shape-cube-half",
    188: "shape-cube-rounded",
    189: "shape-cylinder",
    190: "shape-cylinder-detailed",
    191: "shape-cylinder-half",
    192: "shape-cylinder-half-detailed",
    193: "shape-hexagon",
    194: "shape-hexagon-half",
    195: "shape-hollow-cylinder",
    196: "shape-hollow-cylinder-detailed",
    197: "shape-hollow-cylinder-half",
    198: "shape-hollow-cylinder-half-detailed",
    199: "shape-hollow-hexagon",
    200: "shape-hollow-hexagon-half",
    201: "shape-slope",
    202: "shape-triangular-prism",
    203: "shape-triangular-prism-low",
    204: "stairs",
    205: "stairs-diagonal",
    206: "stairs-diagonal-narrow",
    207: "stairs-diagonal-small",
    208: "stairs-diagonal-small-narrow",
    209: "stairs-narrow",
    210: "stairs-small",
    211: "stairs-small-narrow",
    212: "target-a-round",
    213: "target-a-square",
    214: "target-b-round",
    215: "target-b-square",
    216: "vehicle",
    217: "vehicle-convertible",
    218: "wall",
    918: [
      // -|-
      {
        model: "wall",
      },
      {
        model: "wall",
        correction: {
          rotation: [0, Math.PI / 2, 0],
        },
      },
    ],
    919: [
      // |-
      {
        model: "wall",
      },
      {
        model: "wall",
        correction: {
          rotation: [0, Math.PI / 2, 0],
          scale: [1, 1, 0.4],
          position: [0.3, 0, 0],
        },
      },
    ],
    920: [
      // |-
      {
        model: "wall",
      },
      {
        model: "wall-low",
        correction: {
          rotation: [0, Math.PI / 2, 0],
          scale: [1, 1, 0.4],
          position: [0.3, 0, 0],
        },
      },
    ],
    219: {
      model: "wall-corner",
      correction: { position: [-0.4, 0, 0.4] },
    },
    220: {
      model: "wall-corner-low",
      correction: { position: [-0.4, 0, 0.4] },
    },
    221: {
      model: "wall-corner-rounded",
      correction: { position: [-0.4, 0, 0.4] },
    },
    222: {
      model: "wall-corner-rounded-low",
      correction: { position: [-0.4, 0, 0.4] },
    },
    223: "wall-diagonal",
    224: "wall-diagonal-low",
    225: "wall-doorway",
    226: "wall-doorway-garage",
    227: "wall-doorway-round",
    228: "wall-doorway-sliding",
    229: "wall-doorway-wide",
    230: "wall-doorway-wide-sliding",
    231: "wall-low",
    232: "wall-round",
    233: "wall-round-low",
    234: "wall-window-barred-large",
    235: "wall-window-barred-medium",
    236: "wall-window-barred-small",
    237: "wall-window-cutout-large",
    238: "wall-window-cutout-medium",
    239: "wall-window-cutout-small",
    240: "wall-window-large",
    241: "wall-window-medium",
    242: "wall-window-small",
    243: "weapon-shield",
    244: "weapon-sword",
    245: "wheelchair",
  },
};

export default TileMaps;
